export default {
	"nodes": [
		{"id":"extension","group":"frontend"},
		{"id":"dashboard","group":"frontend"},
		{"id":"api-gateway","group":"aws"},
		{"id":"kafka","group":"aws"},
		{"id":"browsers-api","group":"backend"},
		{"id":"event-injester","group":"backend"},
		{"id":"events-api","group":"backend"},
		{"id":"extension-api","group":"backend"},
		{"id":"identity-provider-api","group":"backend"},
		{"id":"kafka-backup","group":"backend"},
		{"id":"phishing-features","group":"backend"},
		{"id":"policy-api","group":"backend"},
		{"id":"tenants-api","group":"backend"},
		{"id":"tasks","group":"backend"},
		{"id":"dashboard-api","group":"backend"},	
	],
	"links": [
		{"source":"api-gateway","target":"extension","value":3},
		{"source":"api-gateway","target":"dashboard","value":3},
		{"source":"kafka","target":"event-injester","value":3},
		{"source":"kafka","target":"kafka-backup","value":3},
		{"source":"browsers-api","target":"dashboard-api","value":3},
		{"source":"event-injester","target":"events-api","value":3},
		{"source":"event-injester","target":"browsers-api","value":3},
		{"source":"events-api","target":"dashboard-api","value":3},
		{"source":"extension-api","target":"api-gateway","value":3},
		{"source":"extension-api","target":"kafka","value":3},
		{"source":"identity-provider-api","target":"api-gateway","value":3},
		{"source":"phishing-features","target":"extension-api","value":3},
		{"source":"policy-api","target":"extension-api","value":3},
		{"source":"policy-api","target":"dashboard-api","value":3},
		{"source":"tenants-api","target":"dashboard-api","value":3},
		{"source":"tenants-api","target":"policy-api","value":3},
		{"source":"tasks","target":"tenants-api","value":3},
		{"source":"tasks","target":"browsers-api","value":3},
		{"source":"dashboard-api","target":"api-gateway","value":3},
	]
  }
  