export default {
	"nodes": [
		{"name":"extension","id":"extension","group":"frontend"},
		{"name":"dashboard","id":"dashboard","group":"frontend"},
		{"name":"api-gateway","id":"api-gateway","group":"aws"},
		{"name":"kafka","id":"kafka","group":"aws"},
		{"name":"browsers-api","id":"browsers-api","group":"backend"},
		{"name":"event-injester","id":"event-injester","group":"backend"},
		{"name":"events-api","id":"events-api","group":"backend"},
		{"name":"extension-api","id":"extension-api","group":"backend"},
		{"name":"identity-provider-api","id":"identity-provider-api","group":"backend"},
		{"name":"kafka-backup","id":"kafka-backup","group":"backend"},
		{"name":"phishing-features","id":"phishing-features","group":"backend"},
		{"name":"policy-api","id":"policy-api","group":"backend"},
		{"name":"tenants-api","id":"tenants-api","group":"backend"},
		{"name":"tasks","id":"tasks","group":"backend"},
		{"name":"dashboard-api","id":"dashboard-api","group":"backend"},
	],
	"links": [
		{"source":"api-gateway","target":"extension","value":3},
		{"source":"api-gateway","target":"dashboard","value":3},
		{"source":"kafka","target":"event-injester","value":3},
		{"source":"kafka","target":"kafka-backup","value":3},
		{"source":"browsers-api","target":"dashboard-api","value":3},
		{"source":"event-injester","target":"events-api","value":3},
		{"source":"event-injester","target":"browsers-api","value":3},
		{"source":"events-api","target":"dashboard-api","value":3},
		{"source":"extension-api","target":"api-gateway","value":3},
		{"source":"extension-api","target":"kafka","value":3},
		{"source":"identity-provider-api","target":"api-gateway","value":3},
		{"source":"phishing-features","target":"extension-api","value":3},
		{"source":"policy-api","target":"extension-api","value":3},
		{"source":"policy-api","target":"dashboard-api","value":3},
		{"source":"tenants-api","target":"dashboard-api","value":3},
		{"source":"tenants-api","target":"policy-api","value":3},
		{"source":"tasks","target":"tenants-api","value":3},
		{"source":"tasks","target":"browsers-api","value":3},
		{"source":"dashboard-api","target":"api-gateway","value":3},
	]
  }
  